import { ethers, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

/**
 * Deploys FeeEscrow + TokenFactory to the target network and writes the
 * resulting addresses into the frontend at src/lib/contracts/addresses.ts.
 *
 * Usage:
 *   npm run deploy         # Monad Testnet (needs DEPLOYER_PRIVATE_KEY)
 *   npm run deploy:local   # in-process hardhat network
 */
async function main() {
  const [deployer] = await ethers.getSigners();
  const platformWallet =
    process.env.PLATFORM_FEE_WALLET ?? deployer.address;

  console.log("Network:      ", network.name);
  console.log("Deployer:     ", deployer.address);
  console.log("Platform fee →", platformWallet);
  const bal = await ethers.provider.getBalance(deployer.address);
  console.log("Balance:      ", ethers.formatEther(bal), "MON\n");

  // 1) FeeEscrow (owner = deployer, deployer is initial claimer)
  const Escrow = await ethers.getContractFactory("FeeEscrow");
  const escrow = await Escrow.deploy(deployer.address);
  await escrow.waitForDeployment();
  const escrowAddr = await escrow.getAddress();
  console.log("FeeEscrow:    ", escrowAddr);

  // Optionally authorize a separate backend claimer signer.
  const backendClaimer = process.env.ESCROW_CLAIMER_ADDRESS;
  if (backendClaimer && backendClaimer !== deployer.address) {
    const tx = await escrow.setClaimer(backendClaimer, true);
    await tx.wait();
    console.log("  ↳ claimer set:", backendClaimer);
  }

  // 2) TokenFactory
  const Factory = await ethers.getContractFactory("TokenFactory");
  const factory = await Factory.deploy(
    deployer.address,
    escrowAddr,
    platformWallet
  );
  await factory.waitForDeployment();
  const factoryAddr = await factory.getAddress();
  console.log("TokenFactory: ", factoryAddr);

  // 3) Write addresses to the frontend
  const chainId = Number((await ethers.provider.getNetwork()).chainId);
  const out = `// AUTO-GENERATED by contracts/scripts/deploy.ts — do not edit by hand.
// Network: ${network.name} (chainId ${chainId})
export const CONTRACT_ADDRESSES = {
  chainId: ${chainId},
  factory: "${factoryAddr}",
  escrow: "${escrowAddr}",
  platformWallet: "${platformWallet}",
} as const;

export function contractsConfigured(): boolean {
  const zero = "0x0000000000000000000000000000000000000000";
  return (
    (CONTRACT_ADDRESSES.factory as string) !== zero &&
    (CONTRACT_ADDRESSES.escrow as string) !== zero
  );
}
`;

  const target = path.resolve(
    __dirname,
    "../../src/lib/contracts/addresses.ts"
  );
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, out);
  console.log("\n✅ Wrote addresses to", target);

  console.log("\nAdd these to your .env / .env.local:");
  console.log(`NEXT_PUBLIC_FACTORY_ADDRESS=${factoryAddr}`);
  console.log(`NEXT_PUBLIC_ESCROW_ADDRESS=${escrowAddr}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
