// AUTO-GENERATED by contracts/scripts/deploy.ts — do not edit by hand.
// Network: monadTestnet (chainId 10143)
export const CONTRACT_ADDRESSES = {
  chainId: 10143,
  factory: "0x088f55f23a023e0305E58aA382d8C8A4ba21B955",
  escrow: "0x18587f2564dddcc6D6eF10A5012Dd6B1cacC62fB",
  platformWallet: "0x711Be33B799014261De330fcF442384BF7c98E78",
} as const;

export function contractsConfigured(): boolean {
  const zero = "0x0000000000000000000000000000000000000000";
  return (
    (CONTRACT_ADDRESSES.factory as string) !== zero &&
    (CONTRACT_ADDRESSES.escrow as string) !== zero
  );
}
